import "../../static/fonts/MERIFONT.ttf";

import { Button, VerticalBox } from "std-widgets.slint";

struct TileData {
    kind: string,
    environment: bool,
}

component Tile inherits Rectangle {
    in property <bool> tile-color;
    in-out property <string> kind;
    in property <bool> environment;
    private property <bool> active;
    background: tile-color ? #ebecd0 : #969696;

    // TODO
    // only one active tile at a time
    // current player can select only his tiles
    states [
        active when active && !environment: {
            state-area.opacity: 0.5;
        }
        hover when touch-area.has-hover && !environment: {
            state-area.opacity: 0.5;
        }
    ]

    state-area := Rectangle {
        opacity: 0;
        background: #000000;
        animate opacity { duration: 150ms; }
    }

    kind-text := Text {
        font-size: 64px;
        font-family: "Chess Merida";
        color: #000000;
        text: kind;
    }

    touch-area := TouchArea {
        clicked => {
            active = !active;
        }
    }
}

export component ChessBoard {
    private property <length> tile_size: 80px;
    private property <int> columns: 8;
    private property <int> rows: 8;

    width: tile_size * columns;
    height: tile_size * columns;

    in property <[[TileData]]> tiles: [
        [
            { kind:"t" },
            { kind:"m" },
            { kind:"v" },
            { kind:"w" },
            { kind:"l" },
            { kind:"v" },
            { kind:"m" },
            { kind:"t" }
        ],
        [
            { kind:"o" },
            { kind:"o" },
            { kind:"o" },
            { kind:"o" },
            { kind:"o" },
            { kind:"o" },
            { kind:"o" },
            { kind:"o" }
        ],
        [
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true }
        ],
        [
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true }
        ],
        [
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true }
        ],
        [
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true },
            { environment: true }
        ],
        [
            { kind:"p" },
            { kind:"p" },
            { kind:"p" },
            { kind:"p" },
            { kind:"p" },
            { kind:"p" },
            { kind:"p" },
            { kind:"p" }
        ],
        [
            { kind:"r" },
            { kind:"n" },
            { kind:"b" },
            { kind:"q" },
            { kind:"k" },
            { kind:"b" },
            { kind:"n" },
            { kind:"r" }
        ]
    ];
    for row[row_i] in tiles: state-area := Rectangle {
        for column[col_i] in row: Tile {
            x: col_i * tile_size;
            y: row_i * tile_size;
            tile-color: mod((row_i + col_i), 2) == 0;
            width: tile_size;
            height: tile_size;
            kind: column.kind;
            environment: column.environment;
        }
    }
}
